top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/os
builddir     = /u/huang238/a290-js/httpd-2.2.2/os
VPATH        = /u/huang238/a290-js/httpd-2.2.2/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
