##Sch name = JA1
set_property PACKAGE_PIN J1 [get_ports {sck}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sck}]
##Sch name = JA2
set_property PACKAGE_PIN L2 [get_ports {miso}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {miso}]
##Sch name = JA3
set_property PACKAGE_PIN J2 [get_ports {mosi}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {mosi}]
##Sch name = JA4
set_property PACKAGE_PIN G2 [get_ports {cs}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {cs}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sck_IBUF]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
    

    
##7 segment display 
set_property PACKAGE_PIN W7 [get_ports {S[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[0]}] 
set_property PACKAGE_PIN W6 [get_ports {S[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}] 
set_property PACKAGE_PIN U8 [get_ports {S[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[2]}] 
set_property PACKAGE_PIN V8 [get_ports {S[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[3]}] 
set_property PACKAGE_PIN U5 [get_ports {S[4]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[4]}] 
set_property PACKAGE_PIN V5 [get_ports {S[5]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[5]}] 
set_property PACKAGE_PIN U7 [get_ports {S[6]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[6]}] 
    
##connect control signals 
set_property PACKAGE_PIN U2 [get_ports {an[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}] 
set_property PACKAGE_PIN U4 [get_ports {an[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}] 
set_property PACKAGE_PIN V4 [get_ports {an[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}] 
set_property PACKAGE_PIN W4 [get_ports {an[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}] 
    
set_property PACKAGE_PIN W5 [get_ports clk] 
        set_property IOSTANDARD LVCMOS33 [get_ports clk] 
        create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk] 