top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/modules/cache
builddir     = /u/huang238/a290-js/httpd-2.2.2/modules/cache
VPATH        = /u/huang238/a290-js/httpd-2.2.2/modules/cache

include $(top_srcdir)/build/special.mk

