top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/os/unix
builddir     = /u/huang238/a290-js/httpd-2.2.2/os/unix
VPATH        = /u/huang238/a290-js/httpd-2.2.2/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
