top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/modules/aaa
builddir     = /u/huang238/a290-js/httpd-2.2.2/modules/aaa
VPATH        = /u/huang238/a290-js/httpd-2.2.2/modules/aaa

include $(top_srcdir)/build/special.mk

