top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/modules/metadata
builddir     = /u/huang238/a290-js/httpd-2.2.2/modules/metadata
VPATH        = /u/huang238/a290-js/httpd-2.2.2/modules/metadata

include $(top_srcdir)/build/special.mk

