top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/modules/experimental
builddir     = /u/huang238/a290-js/httpd-2.2.2/modules/experimental
VPATH        = /u/huang238/a290-js/httpd-2.2.2/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
