top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/modules/echo
builddir     = /u/huang238/a290-js/httpd-2.2.2/modules/echo
VPATH        = /u/huang238/a290-js/httpd-2.2.2/modules/echo

include $(top_srcdir)/build/special.mk

