top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/server/mpm
builddir     = /u/huang238/a290-js/httpd-2.2.2/server/mpm
VPATH        = /u/huang238/a290-js/httpd-2.2.2/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
