set_property PACKAGE_PIN V17 [get_ports {A[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}] 
set_property PACKAGE_PIN V16 [get_ports {A[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}] 
set_property PACKAGE_PIN W16 [get_ports {A[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}] 
set_property PACKAGE_PIN W17 [get_ports {A[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}] 

##Buttons 
set_property PACKAGE_PIN U18 [get_ports rst] 
    set_property IOSTANDARD LVCMOS33 [get_ports rst] 
set_property PACKAGE_PIN T18 [get_ports W[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports W[0]] 
set_property PACKAGE_PIN W19 [get_ports W[1]] 
    set_property IOSTANDARD LVCMOS33 [get_ports W[1]] 
set_property PACKAGE_PIN T17 [get_ports W[2]] 
    set_property IOSTANDARD LVCMOS33 [get_ports W[2]] 
set_property PACKAGE_PIN U17 [get_ports W[3]] 
    set_property IOSTANDARD LVCMOS33 [get_ports W[3]] 

##7 segment display 
set_property PACKAGE_PIN W7 [get_ports {S[6]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[6]}] 
set_property PACKAGE_PIN W6 [get_ports {S[5]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[5]}] 
set_property PACKAGE_PIN U8 [get_ports {S[4]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[4]}] 
set_property PACKAGE_PIN V8 [get_ports {S[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[3]}] 
set_property PACKAGE_PIN U5 [get_ports {S[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[2]}] 
set_property PACKAGE_PIN V5 [get_ports {S[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}] 
set_property PACKAGE_PIN U7 [get_ports {S[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {S[0]}] 

set_property PACKAGE_PIN U2 [get_ports {an[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}] 
set_property PACKAGE_PIN U4 [get_ports {an[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}] 
set_property PACKAGE_PIN V4 [get_ports {an[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}] 
set_property PACKAGE_PIN W4 [get_ports {an[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}] 

## Clock signal 
set_property PACKAGE_PIN W5 [get_ports clk] 
    set_property IOSTANDARD LVCMOS33 [get_ports clk] 
    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5}[get_ports clk] 