top_srcdir   = /u/huang238/a290-js/httpd-2.2.2
top_builddir = /u/huang238/a290-js/httpd-2.2.2
srcdir       = /u/huang238/a290-js/httpd-2.2.2/server/mpm/prefork
builddir     = /u/huang238/a290-js/httpd-2.2.2/server/mpm/prefork
VPATH        = /u/huang238/a290-js/httpd-2.2.2/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
